export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

export const SET_PRIVATE_KEY = 'SET_PRIVATE_KEY';
export const SET_PUBLIC_KEY = 'SET_PUBLIC_KEY';
export const CLEAR_KEYS = 'CLEAR_KEYS';

export const CREATE_KEY_PAIR = 'CREATE_KEY_PAIR';

export const SET_STORJ_INSTANCE = 'SET_STORJ_INSTANCE';
export const CLEAR_STORJ_INSTANCE = 'CLEAR_STORJ_INSTANCE';

export const SET_BUCKETS = 'SET_BUCKETS';
export const ADD_BUCKET = 'ADD_BUCKET';
export const SET_CURRENT_BUCKET_META = 'SET_CURRENT_BUCKET_META';
export const SET_CURRENT_BUCKET_FILES = 'SET_CURRENT_BUCKET_FILES';
export const CLEAR_BUCKET_STATE = 'CLEAR_BUCKET_STATE';

export const SET_CREDITS = 'SET_CREDITS';
export const SET_DEBITS = 'SET_DEBITS';
export const SET_DEFAULT_PAYMENT_METHOD = 'SET_DEFAULT_PAYMENT_METHOD';
export const CLEAR_DEFAULT_PAYMENT_METHOD = 'CLEAR_DEFAULT_PAYMENT_METHOD';
export const SET_BILLING_DATE = 'SET_BILLING_DATE';
export const SET_DEFAULT_PP_ID = 'SET_DEFAULT_PP_ID';
export const MARK_RETRIEVED = 'MARK_RETRIEVED';
export const SET_NEXT_BILLING_PERIOD = 'SET_NEXT_BILLING_PERIOD';
export const CLEAR_BILLING = 'CLEAR_BILLING';

export const SET_WALLETS = 'SET_WALLETS';

export const SET_STRIPE_TOKEN = 'SET_STRIPE_TOKEN';
export const CLEAR_STRIPE_TOKEN = 'CLEAR_STRIPE_TOKEN';

export const SET_MARKETING = 'SET_MARKETING';
export const CLEAR_MARKETING = 'CLEAR_MARKETING';
