export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

export const SET_PRIVATE_KEY = 'SET_PRIVATE_KEY';
export const SET_PUBLIC_KEY = 'SET_PUBLIC_KEY';
export const CLEAR_PRIVATE_KEY = 'CLEAR_PRIVATE_KEY';

export const CREATE_KEY_PAIR = 'CREATE_KEY_PAIR';

export const SET_STORJ_INSTANCE = 'SET_STORJ_INSTANCE';
export const CLEAR_STORJ_INSTANCE = 'CLEAR_STORJ_INSTANCE';

export const SET_BUCKETS = 'SET_BUCKETS';
export const ADD_BUCKET = 'ADD_BUCKET';
export const SET_CURRENT_BUCKET_META = 'SET_CURRENT_BUCKET_META';
export const SET_CURRENT_BUCKET_FILES = 'SET_CURRENT_BUCKET_FILES';

export const SET_CREDITS = 'SET_CREDITS';
export const SET_DEBITS = 'SET_DEBITS';
